version: '3.3'

services:
        db:
                image: mysql:5.7
                volumes:
                        - ./devmysql:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: toor
                        MYSQL_DATABASE: toor
                        MYSQL_USER: toor
                        MYSQL_PASSWORD: toor
        wordpress:
                depends_on:
                        - db
                working_dir: /var/www/html
                volumes:
                        - ./wp-content:/var/www/html/wp-content
                        - ./wp-uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
                image: wordpress:latest
                ports:
                        - "80:80"
                restart: always
                environment:
                        WORDPRESS_DB_HOST: db:3306
                        WORDPRESS_DB_USER: toor
                        WORDPRESS_DB_PASSWORD: toor
                        WORDPRESS_DB_NAME: toor
